steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/my-php-app:$COMMIT_SHA'
      - '.'

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/my-php-app:$COMMIT_SHA'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'my-php-app'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/my-php-app:$COMMIT_SHA'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars=DB_HOST=35.192.15.69,DB_NAME=image_catalog,DB_USER=appmod-phpapp-user'
      - '--set-secrets=DB_PASS=php-amarcord-db-pass:latest'
      - '--execution-environment=gen2'
      - '--add-volume=name=php_uploads,type=cloud-storage,bucket=awesome-project-489421-images'
      - '--add-volume-mount=volume=php_uploads,mount-path=/var/www/html/uploads/'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/my-php-app:$COMMIT_SHA'

serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/377411193239-compute@developer.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY
